// Objective-C API for talking to ppakma/ue Go package.
//   gobind -lang=objc ppakma/ue
//
// File is generated by gobind. Do not edit.

#ifndef __Ue_H__
#define __Ue_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull UeGenerateUID(void);

#endif
