// Objective-C API for talking to ppakma/networks Go package.
//   gobind -lang=objc ppakma/networks
//
// File is generated by gobind. Do not edit.

#ifndef __Networks_H__
#define __Networks_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void NetworksTestRequest(NSString* _Nullable url);

#endif
