
// Objective-C API for talking to the following Go packages
//
//	ppakma/networks
//
// File is generated by gomobile bind. Do not edit.
#ifndef __NetworksApi_FRAMEWORK_H__
#define __NetworksApi_FRAMEWORK_H__

#include "Networks.objc.h"
#include "Universe.objc.h"

#endif
