
// Objective-C API for talking to the following Go packages
//
//	ppakma/osign
//
// File is generated by gomobile bind. Do not edit.
#ifndef __ObliviousSignatureApi_FRAMEWORK_H__
#define __ObliviousSignatureApi_FRAMEWORK_H__

#include "Osign.objc.h"
#include "Universe.objc.h"

#endif
