// Objective-C API for talking to ppakma/ue Go package.
//   gobind -lang=objc ppakma/ue
//
// File is generated by gobind. Do not edit.

#ifndef __Ue_H__
#define __Ue_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class UeAkmaProtocolBenchmarkStat;
@class UeBenchmarkConfig;
@class UeNormalAkmaProtocolBenchmarkStat;
@class UeObliviousSignClientBenchmarkStat;
@class UeParameterSet;
@class UePingOptions;
@class UePingResult;
@class UeResult;

@interface UeAkmaProtocolBenchmarkStat : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field AkmaProtocolBenchmarkStat.NwRegAFReqTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.NwRegHNReqTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.NwRegHNComTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.NwRegHNFinTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.NwRegAFFinTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.CpRegComTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.CpRegSignTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.CpRegFinTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.NwLoginAfReqTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.NwLoginHNReqTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.NwLoginHNFinTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.NwLoginAFFinTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.CpLoginComTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.CpLoginSignTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.CpLoginFinTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.RegComputationTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.RegNetworkTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.RegTotalTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.LoginComputationTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.LoginNetworkTime with unsupported type: time.Duration

// skipped field AkmaProtocolBenchmarkStat.LoginTotalTime with unsupported type: time.Duration

@end

/**
 * BenchmarkConfig holds the configuration for the benchmark test
 */
@interface UeBenchmarkConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull baseURL;
@property (nonatomic) NSString* _Nonnull requestType;
@property (nonatomic) long concurrency;
@property (nonatomic) long concurrentParams;
// skipped field BenchmarkConfig.Duration with unsupported type: time.Duration

// skipped field BenchmarkConfig.ParamSets with unsupported type: []ppakma/ue.ParameterSet

// skipped field BenchmarkConfig.CommonHeader with unsupported type: map[string]string

@end

@interface UeNormalAkmaProtocolBenchmarkStat : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field NormalAkmaProtocolBenchmarkStat.NwHNReqTime with unsupported type: time.Duration

// skipped field NormalAkmaProtocolBenchmarkStat.NwAFReqTime with unsupported type: time.Duration

// skipped field NormalAkmaProtocolBenchmarkStat.NwAFFinTime with unsupported type: time.Duration

// skipped field NormalAkmaProtocolBenchmarkStat.CpHnReqTime with unsupported type: time.Duration

// skipped field NormalAkmaProtocolBenchmarkStat.CpAFReqTime with unsupported type: time.Duration

// skipped field NormalAkmaProtocolBenchmarkStat.CpAFFinTime with unsupported type: time.Duration

// skipped field NormalAkmaProtocolBenchmarkStat.ComputationTime with unsupported type: time.Duration

// skipped field NormalAkmaProtocolBenchmarkStat.NetworkTime with unsupported type: time.Duration

// skipped field NormalAkmaProtocolBenchmarkStat.TotalTime with unsupported type: time.Duration

@end

@interface UeObliviousSignClientBenchmarkStat : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field ObliviousSignClientBenchmarkStat.KeyGenTime with unsupported type: time.Duration

// skipped field ObliviousSignClientBenchmarkStat.Sign1Time with unsupported type: time.Duration

// skipped field ObliviousSignClientBenchmarkStat.Sign2Time with unsupported type: time.Duration

// skipped field ObliviousSignClientBenchmarkStat.Sign3Time with unsupported type: time.Duration

// skipped field ObliviousSignClientBenchmarkStat.TotalClientTime with unsupported type: time.Duration

@end

/**
 * ParameterSet represents a set of test parameters
 */
@interface UeParameterSet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
// skipped field ParameterSet.Parameters with unsupported type: map[string]interface{}

@end

/**
 * PingOptions configures the ping test
 */
@interface UePingOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) long count;
// skipped field PingOptions.Timeout with unsupported type: time.Duration

// skipped field PingOptions.Interval with unsupported type: time.Duration

@end

/**
 * PingResult stores the results of a ping test
 */
@interface UePingResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull url;
// skipped field PingResult.AverageLatency with unsupported type: time.Duration

@property (nonatomic) double packetLoss;
@property (nonatomic) NSError* _Nullable error;
@end

/**
 * Result represents the benchmark results
 */
@interface UeResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull paramSetName;
// skipped field Result.RequestType with unsupported type: ppakma/ue.RequestType

@property (nonatomic) int64_t totalRequests;
@property (nonatomic) int64_t successfulRequests;
@property (nonatomic) int64_t failedRequests;
// skipped field Result.TotalLatency with unsupported type: time.Duration

// skipped field Result.AverageLatency with unsupported type: time.Duration

@property (nonatomic) double requestsPerSecond;
@end

@interface Ue : NSObject
+ (NSString* _Nonnull) afurl;
+ (void) setAFURL:(NSString* _Nonnull)v;

+ (NSString* _Nonnull) hnurl;
+ (void) setHNURL:(NSString* _Nonnull)v;

@end

FOUNDATION_EXPORT void UeBenchmarkRequests(void);

// skipped function DefaultPingOptions with unsupported parameter or return types


FOUNDATION_EXPORT NSData* _Nullable UeGenerateRandomness(void);

FOUNDATION_EXPORT NSString* _Nonnull UeGenerateSUPI(void);

FOUNDATION_EXPORT NSString* _Nonnull UeGenerateUID(void);

FOUNDATION_EXPORT NSString* _Nonnull UeRunBenchmark2POS(long n);

FOUNDATION_EXPORT NSString* _Nonnull UeRunBenchmarkAmortized2POS(long n);

FOUNDATION_EXPORT NSString* _Nonnull UeRunBenchmarkAmortizedProtocol(long n, NSString* _Nullable hnUrl, NSString* _Nullable afUrl);

FOUNDATION_EXPORT NSString* _Nonnull UeRunBenchmarkNormalProtocol(long n, NSString* _Nullable hnUrl, NSString* _Nullable afUrl);

FOUNDATION_EXPORT NSString* _Nonnull UeRunBenchmarkProtocol(long n, NSString* _Nullable hnUrl, NSString* _Nullable afUrl);

// skipped function TestLatencyWithTCP with unsupported parameter or return types


#endif
