
// Objective-C API for talking to the following Go packages
//
//	ppakma/ue
//
// File is generated by gomobile bind. Do not edit.
#ifndef __UEBechmarkApi_FRAMEWORK_H__
#define __UEBechmarkApi_FRAMEWORK_H__

#include "Ue.objc.h"
#include "Universe.objc.h"

#endif
